# Generated by Django 5.0.2 on 2024-03-19 09:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("homepage", "0002_remove_photo_uploader_ticket_review_userfollows_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="media"),
        ),
    ]
